/**
 * COVID-19 Local API
 * API to get local help information about COVID-19 (hotlines, websites, test sites, health departments)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HealthDepartment from './HealthDepartment';
import Hotline from './Hotline';
import Place from './Place';
import TestSite from './TestSite';
import Website from './Website';

/**
 * The ResultsList model module.
 * @module model/ResultsList
 * @version 0.1.0
 */
class ResultsList {
    /**
     * Constructs a new <code>ResultsList</code>.
     * @alias module:model/ResultsList
     * @param place {module:model/Place} 
     */
    constructor(place) { 
        
        ResultsList.initialize(this, place);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, place) { 
        obj['place'] = place;
    }

    /**
     * Constructs a <code>ResultsList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResultsList} obj Optional instance to populate.
     * @return {module:model/ResultsList} The populated <code>ResultsList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResultsList();

            if (data.hasOwnProperty('place')) {
                obj['place'] = Place.constructFromObject(data['place']);
            }
            if (data.hasOwnProperty('hotlines')) {
                obj['hotlines'] = ApiClient.convertToType(data['hotlines'], [Hotline]);
            }
            if (data.hasOwnProperty('websites')) {
                obj['websites'] = ApiClient.convertToType(data['websites'], [Website]);
            }
            if (data.hasOwnProperty('test_sites')) {
                obj['test_sites'] = ApiClient.convertToType(data['test_sites'], [TestSite]);
            }
            if (data.hasOwnProperty('health_departments')) {
                obj['health_departments'] = ApiClient.convertToType(data['health_departments'], [HealthDepartment]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Place} place
 */
ResultsList.prototype['place'] = undefined;

/**
 * @member {Array.<module:model/Hotline>} hotlines
 */
ResultsList.prototype['hotlines'] = undefined;

/**
 * @member {Array.<module:model/Website>} websites
 */
ResultsList.prototype['websites'] = undefined;

/**
 * @member {Array.<module:model/TestSite>} test_sites
 */
ResultsList.prototype['test_sites'] = undefined;

/**
 * @member {Array.<module:model/HealthDepartment>} health_departments
 */
ResultsList.prototype['health_departments'] = undefined;






export default ResultsList;

