/**
 * COVID-19 Local API
 * API to get local help information about COVID-19 (hotlines, websites, test sites, health departments)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TestSite model module.
 * @module model/TestSite
 * @version 0.1.0
 */
class TestSite {
    /**
     * Constructs a new <code>TestSite</code>.
     * @alias module:model/TestSite
     */
    constructor() { 
        
        TestSite.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TestSite</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TestSite} obj Optional instance to populate.
     * @return {module:model/TestSite} The populated <code>TestSite</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TestSite();

            if (data.hasOwnProperty('country_code')) {
                obj['country_code'] = ApiClient.convertToType(data['country_code'], 'String');
            }
            if (data.hasOwnProperty('lat')) {
                obj['lat'] = ApiClient.convertToType(data['lat'], 'Number');
            }
            if (data.hasOwnProperty('lon')) {
                obj['lon'] = ApiClient.convertToType(data['lon'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('street')) {
                obj['street'] = ApiClient.convertToType(data['street'], 'String');
            }
            if (data.hasOwnProperty('zip_code')) {
                obj['zip_code'] = ApiClient.convertToType(data['zip_code'], 'Number');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('address_supplement')) {
                obj['address_supplement'] = ApiClient.convertToType(data['address_supplement'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('website')) {
                obj['website'] = ApiClient.convertToType(data['website'], 'String');
            }
            if (data.hasOwnProperty('operating_hours')) {
                obj['operating_hours'] = ApiClient.convertToType(data['operating_hours'], 'String');
            }
            if (data.hasOwnProperty('appointment_required')) {
                obj['appointment_required'] = ApiClient.convertToType(data['appointment_required'], 'Boolean');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('sources')) {
                obj['sources'] = ApiClient.convertToType(data['sources'], 'String');
            }
            if (data.hasOwnProperty('distance')) {
                obj['distance'] = ApiClient.convertToType(data['distance'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} country_code
 */
TestSite.prototype['country_code'] = undefined;

/**
 * @member {Number} lat
 */
TestSite.prototype['lat'] = undefined;

/**
 * @member {Number} lon
 */
TestSite.prototype['lon'] = undefined;

/**
 * @member {String} name
 */
TestSite.prototype['name'] = undefined;

/**
 * @member {String} street
 */
TestSite.prototype['street'] = undefined;

/**
 * @member {Number} zip_code
 */
TestSite.prototype['zip_code'] = undefined;

/**
 * @member {String} city
 */
TestSite.prototype['city'] = undefined;

/**
 * @member {String} address_supplement
 */
TestSite.prototype['address_supplement'] = undefined;

/**
 * @member {String} phone
 */
TestSite.prototype['phone'] = undefined;

/**
 * @member {String} website
 */
TestSite.prototype['website'] = undefined;

/**
 * @member {String} operating_hours
 */
TestSite.prototype['operating_hours'] = undefined;

/**
 * @member {Boolean} appointment_required
 */
TestSite.prototype['appointment_required'] = undefined;

/**
 * @member {String} description
 */
TestSite.prototype['description'] = undefined;

/**
 * @member {String} sources
 */
TestSite.prototype['sources'] = undefined;

/**
 * @member {Number} distance
 */
TestSite.prototype['distance'] = undefined;






export default TestSite;

