/**
 * COVID-19 Local API
 * API to get local help information about COVID-19 (hotlines, websites, test sites, health departments)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Website model module.
 * @module model/Website
 * @version 0.1.0
 */
class Website {
    /**
     * Constructs a new <code>Website</code>.
     * @alias module:model/Website
     */
    constructor() { 
        
        Website.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Website</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Website} obj Optional instance to populate.
     * @return {module:model/Website} The populated <code>Website</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Website();

            if (data.hasOwnProperty('country_code')) {
                obj['country_code'] = ApiClient.convertToType(data['country_code'], 'String');
            }
            if (data.hasOwnProperty('place')) {
                obj['place'] = ApiClient.convertToType(data['place'], 'String');
            }
            if (data.hasOwnProperty('geonames_id')) {
                obj['geonames_id'] = ApiClient.convertToType(data['geonames_id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('operator')) {
                obj['operator'] = ApiClient.convertToType(data['operator'], 'String');
            }
            if (data.hasOwnProperty('website')) {
                obj['website'] = ApiClient.convertToType(data['website'], 'String');
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('sources')) {
                obj['sources'] = ApiClient.convertToType(data['sources'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} country_code
 */
Website.prototype['country_code'] = undefined;

/**
 * @member {String} place
 */
Website.prototype['place'] = undefined;

/**
 * @member {Number} geonames_id
 */
Website.prototype['geonames_id'] = undefined;

/**
 * @member {String} name
 */
Website.prototype['name'] = undefined;

/**
 * @member {String} operator
 */
Website.prototype['operator'] = undefined;

/**
 * @member {String} website
 */
Website.prototype['website'] = undefined;

/**
 * @member {String} category
 */
Website.prototype['category'] = undefined;

/**
 * @member {String} description
 */
Website.prototype['description'] = undefined;

/**
 * @member {String} sources
 */
Website.prototype['sources'] = undefined;






export default Website;

