/**
 * COVID-19 Local API
 * API to get local help information about COVID-19 (hotlines, websites, test sites, health departments)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Covid19LocalApi);
  }
}(this, function(expect, Covid19LocalApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Covid19LocalApi.HealthDepartment();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('HealthDepartment', function() {
    it('should create an instance of HealthDepartment', function() {
      // uncomment below and update the code to test HealthDepartment
      //var instane = new Covid19LocalApi.HealthDepartment();
      //expect(instance).to.be.a(Covid19LocalApi.HealthDepartment);
    });

    it('should have the property countryCode (base name: "country_code")', function() {
      // uncomment below and update the code to test the property countryCode
      //var instane = new Covid19LocalApi.HealthDepartment();
      //expect(instance).to.be();
    });

    it('should have the property place (base name: "place")', function() {
      // uncomment below and update the code to test the property place
      //var instane = new Covid19LocalApi.HealthDepartment();
      //expect(instance).to.be();
    });

    it('should have the property geonamesId (base name: "geonames_id")', function() {
      // uncomment below and update the code to test the property geonamesId
      //var instane = new Covid19LocalApi.HealthDepartment();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new Covid19LocalApi.HealthDepartment();
      //expect(instance).to.be();
    });

    it('should have the property department (base name: "department")', function() {
      // uncomment below and update the code to test the property department
      //var instane = new Covid19LocalApi.HealthDepartment();
      //expect(instance).to.be();
    });

    it('should have the property street (base name: "street")', function() {
      // uncomment below and update the code to test the property street
      //var instane = new Covid19LocalApi.HealthDepartment();
      //expect(instance).to.be();
    });

    it('should have the property zipCode (base name: "zip_code")', function() {
      // uncomment below and update the code to test the property zipCode
      //var instane = new Covid19LocalApi.HealthDepartment();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instane = new Covid19LocalApi.HealthDepartment();
      //expect(instance).to.be();
    });

    it('should have the property addressSupplement (base name: "address_supplement")', function() {
      // uncomment below and update the code to test the property addressSupplement
      //var instane = new Covid19LocalApi.HealthDepartment();
      //expect(instance).to.be();
    });

    it('should have the property phone (base name: "phone")', function() {
      // uncomment below and update the code to test the property phone
      //var instane = new Covid19LocalApi.HealthDepartment();
      //expect(instance).to.be();
    });

    it('should have the property fax (base name: "fax")', function() {
      // uncomment below and update the code to test the property fax
      //var instane = new Covid19LocalApi.HealthDepartment();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instane = new Covid19LocalApi.HealthDepartment();
      //expect(instance).to.be();
    });

    it('should have the property website (base name: "website")', function() {
      // uncomment below and update the code to test the property website
      //var instane = new Covid19LocalApi.HealthDepartment();
      //expect(instance).to.be();
    });

    it('should have the property sources (base name: "sources")', function() {
      // uncomment below and update the code to test the property sources
      //var instane = new Covid19LocalApi.HealthDepartment();
      //expect(instance).to.be();
    });

  });

}));
