/**
 * COVID-19 Local API
 * API to get local help information about COVID-19 (hotlines, websites, test sites, health departments)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Covid19LocalApi);
  }
}(this, function(expect, Covid19LocalApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Covid19LocalApi.Place();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Place', function() {
    it('should create an instance of Place', function() {
      // uncomment below and update the code to test Place
      //var instane = new Covid19LocalApi.Place();
      //expect(instance).to.be.a(Covid19LocalApi.Place);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new Covid19LocalApi.Place();
      //expect(instance).to.be();
    });

    it('should have the property geonamesId (base name: "geonames_id")', function() {
      // uncomment below and update the code to test the property geonamesId
      //var instane = new Covid19LocalApi.Place();
      //expect(instance).to.be();
    });

    it('should have the property searchProvider (base name: "search_provider")', function() {
      // uncomment below and update the code to test the property searchProvider
      //var instane = new Covid19LocalApi.Place();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instane = new Covid19LocalApi.Place();
      //expect(instance).to.be();
    });

    it('should have the property countryCode (base name: "country_code")', function() {
      // uncomment below and update the code to test the property countryCode
      //var instane = new Covid19LocalApi.Place();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instane = new Covid19LocalApi.Place();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new Covid19LocalApi.Place();
      //expect(instance).to.be();
    });

    it('should have the property lat (base name: "lat")', function() {
      // uncomment below and update the code to test the property lat
      //var instane = new Covid19LocalApi.Place();
      //expect(instance).to.be();
    });

    it('should have the property lon (base name: "lon")', function() {
      // uncomment below and update the code to test the property lon
      //var instane = new Covid19LocalApi.Place();
      //expect(instance).to.be();
    });

  });

}));
