/**
 * COVID-19 Local API
 * API to get local help information about COVID-19 (hotlines, websites, test sites, health departments)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Covid19LocalApi);
  }
}(this, function(expect, Covid19LocalApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Covid19LocalApi.ResultsList();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ResultsList', function() {
    it('should create an instance of ResultsList', function() {
      // uncomment below and update the code to test ResultsList
      //var instane = new Covid19LocalApi.ResultsList();
      //expect(instance).to.be.a(Covid19LocalApi.ResultsList);
    });

    it('should have the property place (base name: "place")', function() {
      // uncomment below and update the code to test the property place
      //var instane = new Covid19LocalApi.ResultsList();
      //expect(instance).to.be();
    });

    it('should have the property hotlines (base name: "hotlines")', function() {
      // uncomment below and update the code to test the property hotlines
      //var instane = new Covid19LocalApi.ResultsList();
      //expect(instance).to.be();
    });

    it('should have the property websites (base name: "websites")', function() {
      // uncomment below and update the code to test the property websites
      //var instane = new Covid19LocalApi.ResultsList();
      //expect(instance).to.be();
    });

    it('should have the property testSites (base name: "test_sites")', function() {
      // uncomment below and update the code to test the property testSites
      //var instane = new Covid19LocalApi.ResultsList();
      //expect(instance).to.be();
    });

    it('should have the property healthDepartments (base name: "health_departments")', function() {
      // uncomment below and update the code to test the property healthDepartments
      //var instane = new Covid19LocalApi.ResultsList();
      //expect(instance).to.be();
    });

  });

}));
