/**
 * COVID-19 Local API
 * API to get local help information about COVID-19 (hotlines, websites, test sites, health departments)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Covid19LocalApi);
  }
}(this, function(expect, Covid19LocalApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Covid19LocalApi.TestSite();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TestSite', function() {
    it('should create an instance of TestSite', function() {
      // uncomment below and update the code to test TestSite
      //var instane = new Covid19LocalApi.TestSite();
      //expect(instance).to.be.a(Covid19LocalApi.TestSite);
    });

    it('should have the property countryCode (base name: "country_code")', function() {
      // uncomment below and update the code to test the property countryCode
      //var instane = new Covid19LocalApi.TestSite();
      //expect(instance).to.be();
    });

    it('should have the property lat (base name: "lat")', function() {
      // uncomment below and update the code to test the property lat
      //var instane = new Covid19LocalApi.TestSite();
      //expect(instance).to.be();
    });

    it('should have the property lon (base name: "lon")', function() {
      // uncomment below and update the code to test the property lon
      //var instane = new Covid19LocalApi.TestSite();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new Covid19LocalApi.TestSite();
      //expect(instance).to.be();
    });

    it('should have the property street (base name: "street")', function() {
      // uncomment below and update the code to test the property street
      //var instane = new Covid19LocalApi.TestSite();
      //expect(instance).to.be();
    });

    it('should have the property zipCode (base name: "zip_code")', function() {
      // uncomment below and update the code to test the property zipCode
      //var instane = new Covid19LocalApi.TestSite();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instane = new Covid19LocalApi.TestSite();
      //expect(instance).to.be();
    });

    it('should have the property addressSupplement (base name: "address_supplement")', function() {
      // uncomment below and update the code to test the property addressSupplement
      //var instane = new Covid19LocalApi.TestSite();
      //expect(instance).to.be();
    });

    it('should have the property phone (base name: "phone")', function() {
      // uncomment below and update the code to test the property phone
      //var instane = new Covid19LocalApi.TestSite();
      //expect(instance).to.be();
    });

    it('should have the property website (base name: "website")', function() {
      // uncomment below and update the code to test the property website
      //var instane = new Covid19LocalApi.TestSite();
      //expect(instance).to.be();
    });

    it('should have the property operatingHours (base name: "operating_hours")', function() {
      // uncomment below and update the code to test the property operatingHours
      //var instane = new Covid19LocalApi.TestSite();
      //expect(instance).to.be();
    });

    it('should have the property appointmentRequired (base name: "appointment_required")', function() {
      // uncomment below and update the code to test the property appointmentRequired
      //var instane = new Covid19LocalApi.TestSite();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new Covid19LocalApi.TestSite();
      //expect(instance).to.be();
    });

    it('should have the property sources (base name: "sources")', function() {
      // uncomment below and update the code to test the property sources
      //var instane = new Covid19LocalApi.TestSite();
      //expect(instance).to.be();
    });

    it('should have the property distance (base name: "distance")', function() {
      // uncomment below and update the code to test the property distance
      //var instane = new Covid19LocalApi.TestSite();
      //expect(instance).to.be();
    });

  });

}));
