/**
 * COVID-19 Local API
 * API to get local help information about COVID-19 (hotlines, websites, test sites, health departments)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import HTTPValidationError from './model/HTTPValidationError';
import HealthDepartment from './model/HealthDepartment';
import Hotline from './model/Hotline';
import Place from './model/Place';
import ResultsList from './model/ResultsList';
import TestSite from './model/TestSite';
import ValidationError from './model/ValidationError';
import Website from './model/Website';
import DefaultApi from './api/DefaultApi';


/**
* API_to_get_local_help_information_about_COVID_19__hotlines_websites_test_sites_health_departments.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Covid19LocalApi = require('index'); // See note below*.
* var xxxSvc = new Covid19LocalApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Covid19LocalApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Covid19LocalApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Covid19LocalApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The HTTPValidationError model constructor.
     * @property {module:model/HTTPValidationError}
     */
    HTTPValidationError,

    /**
     * The HealthDepartment model constructor.
     * @property {module:model/HealthDepartment}
     */
    HealthDepartment,

    /**
     * The Hotline model constructor.
     * @property {module:model/Hotline}
     */
    Hotline,

    /**
     * The Place model constructor.
     * @property {module:model/Place}
     */
    Place,

    /**
     * The ResultsList model constructor.
     * @property {module:model/ResultsList}
     */
    ResultsList,

    /**
     * The TestSite model constructor.
     * @property {module:model/TestSite}
     */
    TestSite,

    /**
     * The ValidationError model constructor.
     * @property {module:model/ValidationError}
     */
    ValidationError,

    /**
     * The Website model constructor.
     * @property {module:model/Website}
     */
    Website,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
